/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import tools.Connections;

/**
 *
 * @author ASUS
 */
public class Report extends javax.swing.JInternalFrame {

  
    Connections connections;
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;

    /**
     * Creates new form Report
     */
    public Report(String nama_file) {
        initComponents();
        
        report(new Connections().getConnection(),nama_file);
    }

//    private void report() {
//        try {
//            File file = new File("src/ireport/ReportRegion.jrxml");
//            Map param = new HashMap();
//            jasperDesign = JRXmlLoader.load(file);
//            jasperReport = JasperCompileManager.compileReport(jasperDesign);
// //untuk masukan ke container pakai JRViewer
//            JRViewer viewer = new JRViewer(jasperPrint);
//            Container c = getContentPane();
//            c.setLayout(new BorderLayout());
//            c.add(viewer);
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
 public void report(Connection connection ,String nama_file) {
        try {
            File file = new File("src/ireport/Report"+nama_file+".jrxml");
            Map param = new HashMap();
            jasperDesign = JRXmlLoader.load(file);
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, connection);
// untuk masukan ke container pakai JRViewer
            JRViewer viewer = new JRViewer(jasperPrint);
            Container c = getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viewer);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
